apiVersion: placement.kubernetes-fleet.io/v1
kind: ResourcePlacement
metadata:
  name: podinfo-flux
  namespace: flux-system
spec:
  resourceSelectors:
    - group: source.toolkit.fluxcd.io
      version: v1
      kind: OCIRepository
      name: podinfo

    - group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: podinfo

  policy:
    placementType: PickAll
  strategy:
    type: RollingUpdatekub