apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux2
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/fluxcd/charts/flux2
no-loc:
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux2
  namespace: flux-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: flux2