
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: aks-store-demo-source
  namespace: aks-store-demo
spec:
  interval: 10m
  url: oci://ghcr.io/sjwaight/aks-store-demo-flux-gitless
  ref:
    tag: 2.2.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aks-store-demo
  namespace: aks-store-demo
spec:
  interval: 10m
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: aks-store-demo-source
  targetNamespace: aks-store-demo