apiVersion: placement.kubernetes-fleet.io/v1
kind: ResourcePlacement
metadata:
  name: aks-store-oci
  namespace: aks-store-demo
spec:
  resourceSelectors:
    - group: source.toolkit.fluxcd.io
      version: v1
      kind: OCIRepository
      name: aks-store-demo-source

    - group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: aks-store-demo

  policy:
    placementType: PickFixed
    clusterNames:
      - aks-member-place-01-fm
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 25%