apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: aks-store-demo
  namespace: flux-system
spec:
  interval: 5m
  provider: generic
  url: oci://ghcr.io/sjwaight/aks-store-demo-flux-gitless
  ref:
    tag: latest
